### PR TITLE
Add Support for Textareas and Selects

### PR DESCRIPTION
**Pull request by jaymiejones86**
This is a recreation of #13 with the requested updates to keep it moving.

### CODE REVIEW

**Comment by KrunchMuffin** [comment]
This isn't working for me. Using Bootstrap 3.

**Comment by mufaddalmw** [comment]
I'm using latest library for this and still it is not working with textarea, any thing which I'm missing?

**Comment by mufaddalmw** [comment]
Sorry my bad I was using :
    $('input.floatlabel').floatlabel();
instead of
    $('.floatlabel').floatlabel();

**Comment by derpoho** [comment]
Sorry, this is currently not in our scope of the plugin. You can still fork and release if you want!

**Pull request closed without merging**
